#version 430

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

//layout (std430, binding = 1) writeonly buffer out_layout
//{
//    vec4 colors[];
//};

layout (std430, binding = 0) buffer in_layout
{
    vec4 positions[];
};

uniform sampler2D tex_image[3];
uniform mat3 cam_r[3];
uniform vec3 cam_t[3];
uniform mat3 cam_k;

uniform int x;
uniform int y;

void main()
{
    uint idx = gl_GlobalInvocationID.x * y + gl_GlobalInvocationID.y;
    vec3 pos = positions[idx].xyz;
    vec2[3] d_pixels;
    vec4[3] local_colors;
    positions[idx] = vec4(0);

    for (int i = 0; i < 3; ++i)
    {
        vec3 p_tmp = cam_r[i] * (pos - cam_t[i]);
        float dist = p_tmp.z;
        p_tmp /= p_tmp.z;
        vec2 p_c;
        p_c.x = cam_k[0][0] * p_tmp.x + cam_k[0][2];
        p_c.y = cam_k[1][1] * -p_tmp.y + cam_k[1][2];
        if (dist > 0 && p_c.x >= 0 && p_c.x <= 960 && p_c.y >= 0 && p_c.y <= 600)
        {
            d_pixels[i] = p_c;
            local_colors[i] = texture(tex_image[i], vec2(p_c.x / 960.0f, p_c.y / 600.0f));
            positions[idx] = texture(tex_image[i], vec2(p_c.x / 960.0f, p_c.y / 600.0f));
        }
        else
        {
            d_pixels[i] = vec2(0);
            local_colors[i] = vec4(0);
        }
    }

//    vec4 weighted_color = vec4(0);
//    for (int i = 0; i < 3; i++)
//    {
//        if(local_colors[i] != vec4(0))
//        {
//            weighted_color
//        }
//        if (d_pixels[i].z > 0 && d_pixels[i].x >= 0 && d_pixels[i].x <= 960 && d_pixels[i].y >= 0 && d_pixels[i].y <= 600)
//        {
//            local_colors[i] = texture(tex_image[i], vec2(d_pixels[i].x / 960.0f, d_pixels[i].y / 600.0f));
//        }
//    }
}