#version 430

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) buffer out_layout
{
    vec3 colors[];
};

layout (binding = 1) buffer in_layout
{
    vec3 positions[];
};

uniform sampler2D tex_image[3];
uniform mat3 cam_r[3];
uniform vec3 cam_t[3];
uniform mat3 cam_k;

uniform int x;
uniform int y;

void main()
{
    uint idx = gl_GlobalInvocationID.x * y + gl_GlobalInvocationID.y;
    vec3 pos = positions[idx];

    for (int i = 0; i < 3; ++i)
    {
        vec3 p_tmp = cam_r[i] * (pos - cam_t[i]);
        float dist = p_tmp.z;
        p_tmp /= p_tmp.z;
        vec2 p_c;
        p_c.x = cam_k[0][0] * p_tmp.x + cam_k[0][2];
        p_c.y = cam_k[1][1] * -p_tmp.y + cam_k[1][2];
        if (dist > 0 && p_c.x >= 0 && p_c.x <= 960 && p_c.y >= 0 && p_c.y <= 600)
        {
            colors[idx] = texture(tex_image[i], vec2(p_c.x / 960.0f, p_c.y / 600.0f)).xyz;
        }
        else
        {
//            colors[idx] = vec3(0);
        }
    }
}